### ISSUE TITLE
debian hoodie hapi debug against iriscouch instance.

### ISSUE THREAD

**Issue by xpollen8** [hoodiehq/discussion#65]
fresh hoodie install - trying to get it to use an iriscouch.. but getting hapi debug message which repeats every 15 seconds or so.

iris futon shows that the expected "app/plugins" databases were created.

```
debian@debian:~/my-first-hoodie$ hoodie start

Version: 0.6.2 (node v0.10.34, npm 2.1.6, platform: linux)

Initializing...
Using remote CouchDB: https://XXXX.iriscouch.com:6984/
Waiting for CouchDB ... SUCCESS
WWW:    http://127.0.0.1:6004
Admin:  http://127.0.0.1:6005
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'
All plugins started.

Hoodie app is running!
WWW:    http://127.0.0.1:6004
Admin:  http://127.0.0.1:6005
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'

Debug: hapi, internal, implementation, error 
    TypeError: Cannot call method 'code' of undefined
    at internals.addCorsAndBearerToken (/home/debian/my-first-hoodie/node_modules/hoodie-server/lib/server/plugins/api/index.js:32:18)
    at /home/debian/my-first-hoodie/node_modules/hoodie-server/node_modules/hapi/node_modules/h2o2/lib/index.js:139:52
    at finish (/home/debian/my-first-hoodie/node_modules/hoodie-server/node_modules/wreck/lib/index.js:92:20)
    at wrapped (/home/debian/my-first-hoodie/node_modules/hoodie-server/node_modules/wreck/node_modules/hoek/lib/index.js:798:20)
    at ClientRequest.onError (/home/debian/my-first-hoodie/node_modules/hoodie-server/node_modules/wreck/lib/index.js:101:16)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1552:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1400:19)
```

**Comment by gr2m** [comment]
sorry we never got back to you @xpollen8, that certainly was not intended! Hope you don’t mind me closing this issue though due to inactivity. 

By the way, we have an all new Hoodie, much easier to understand / debug: https://github.com/hoodiehq/hoodie. Here is an example app: https://github.com/hoodiehq/hoodie-app-tracker
